### ISSUE TITLE
Socket Family issue

### ISSUE THREAD

**Issue by sunlanchang** [bowen-xu/aio_rpc#1]
# 环境
Macbook Pro(M1芯片)
Python 3.9.12

# 问题
执行`python test_server.py`后报错如下所示:
```
(AscellaQRIS) ➜  aio_rpc git:(main) python test_server.py
====================IO Process====================
family:  1
Traceback (most recent call last):
  File "/Users/chris/Workspace/aio_rpc/test_server.py", line 42, in <module>
    server.run()
  File "/Users/chris/Workspace/aio_rpc/aio_rpc/server.py", line 164, in run
    self.init()
  File "/Users/chris/Workspace/aio_rpc/aio_rpc/server.py", line 55, in init
    lsock, addr, port = build_socket()
  File "/Users/chris/Workspace/aio_rpc/aio_rpc/utils.py", line 35, in build_socket
    raise ValueError("Only AF_INET and AF_INET6 socket address families ")
ValueError: Only AF_INET and AF_INET6 socket address families
```
# 原因分析
**直接原因**

经过调试, Mac是支持AF_UNIX,在`utils.py`中`family = AF_UNIX`执行后下面的else走到了raise ValueError的分支判断.

**进一步分析**

[socket文档中](https://docs.python.org/3/library/socket.html)说到:
_A pair (host, port) is used for the AF_INET address family, where host is a string representing either a hostname in internet domain notation like 'daring.cwi.nl' or an IPv4 address like '100.50.200.5', and port is an integer._
所以对于`AF_UNIX`并不能使用`bind((host, port))`方式进行bind.

```
def build_socket(family=None, type=SOCK_STREAM, proto=0) -> Tuple[socket, str, str]:
    '''
    建立socket
    '''
    if family is None:
        try:
            family = AF_UNIX
        except NameError:
            family = AF_INET
    if family == AF_INET:
        host = _LOCALHOST
    elif family == AF_INET6:
        host = _LOCALHOST_V6
    else:
        raise ValueError("Only AF_INET and AF_INET6 socket address families ")

    lsock = socket(family, type, proto)
    
    lsock.bind((host, 0))

    # On IPv6, ignore flow_info and scope_id
    addr, port = lsock.getsockname()[:2]
    return lsock, addr, port
```

# 解决方案
1. `AF_UNIX`主要用于单个机器通信, `AF_INET`可以跨机器通信但是效率低, 不过为了代码简单可以都使用`AF_INET`.
2. [为`AF_UNIX`单独写code](http://www.coolpython.net/python_senior/network/unix-socket.html)

**Comment by bowen-xu** [comment]
Thanks for posting the bug!
I debug `aio_rpc` on Windows, however, Unix Domain Socket (UDS) should be applied on MacOS or Linux, and `aio_rpc` doesn't support UDS well. It should be fixed soon.

**Comment by bowen-xu** [comment]
5515edd60569201f198557a350622d73d8bcc047
Bug is fixed. Please test again.

**Comment by bowen-xu** [comment]
5515edd60569201f198557a350622d73d8bcc047
The bug has been fixed (I ran the `test_server.py` and `test_client.py` on Linux and nothing error occurred). Please test again.
Don't forget to upgrade `aiosock` to the newest version (1.0.5).
